version: '3'

services: 

  web:
    build: .
    container_name: app
    image: alotropo/django
    command: python manage.py runserver 0.0.0.0:8000
    networks: 
      - node-network
    volumes: 
      - .:/code
      - ./static:/code/static/
    tty: true
    # env_file:
    #   - ./.env
    ports: 
      - 8000:8000
    depends_on: 
       - db

  db:
    image: postgres
    container_name: test_deploy_db
    volumes:
      - /data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello

    ports:
      - 5432:5432
    networks: 
      - node-network

  nginx:
    build: ./nginx
    image: alotropo/nginx
    container_name: test_deploy_nginx
    networks: 
      - node-network
    # volumes:
    # #   - staticfiles:/app/static/
    #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web

networks: 
  node-network:
    driver: bridge  