name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest
  deploy:
    name: CD
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Build Docker image
    #   run: |
    #     docker build -t alotropo/django .
    #     docker tag alotropo/django alotropo/django:latest
    #     docker build -t alotropo/nginx ./nginx
    #     docker tag alotropo/nginx alotropo/nginx:latest



    # - name: Push Docker image to registry
    #   run: |
    #     echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    #     docker push alotropo/django:latest
    #     docker push alotropo/nginx:latest

    - name: Deploy to Ubuntu Server
      run: |
        echo "${{ secrets.SECRET_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -i ssh_key.pem ${{ secrets.USER }}@${{ secrets.SSH_HOST }} "echo fazendo alguns testes"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }}