name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     max-parallel: 4
  #     matrix:
  #       python-version: [3.8]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install Dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #   - name: Run Tests
  #     run: |
  #       pytest
        
  deploy:
    name: CD
    # needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2


    # - name: Build Docker image
    #   run: |
    #     docker build -t alotropo/django .
    #     docker tag alotropo/django alotropo/django:latest
    #     docker build -t alotropo/nginx ./nginx
    #     docker tag alotropo/nginx alotropo/nginx:latest

    # - name: Push Docker image to registry
    #   run: |
    #     echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    #     docker push alotropo/django:latest
    #     docker push alotropo/nginx:latest

    - name: Checkout code
      uses: appleboy/ssh-action@master
      env:
        USER_PASS: "${{ secrets.USER_PASSWORD }}"
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: USER_PASS
        script: | 
                  echo "USER_PASS: $USER_PASS"
                #  echo $USER_PASS | sudo -S docker ps



